[package]
name = "metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
id3 = "1.16.2"
image = "0.25.6"
rfd = "0.15.3"
symphonia = { version = "0.5", features = ["mp3"] }
open = "5.3.2"


